//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricityMeterMaster
    {
        public ElectricityMeterMaster()
        {
            this.ElectricityUnitReadings = new HashSet<ElectricityUnitReading>();
            this.PropertyMeterMappings = new HashSet<PropertyMeterMapping>();
            this.RentalProperties = new HashSet<RentalProperty>();
        }
    
        public int Key { get; set; }
        public int MeterNo { get; set; }
        public int MeterReadingStart { get; set; }
        public Nullable<int> OldMeterParentKey { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public Nullable<System.DateTime> DeactivationDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ElectricityUnitReading> ElectricityUnitReadings { get; set; }
        public virtual ICollection<PropertyMeterMapping> PropertyMeterMappings { get; set; }
        public virtual ICollection<RentalProperty> RentalProperties { get; set; }
    }
}
