//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricityUnitReading
    {
        public int Key { get; set; }
        public int MeterKey { get; set; }
        public System.DateTime ReadingForMonth { get; set; }
        public System.DateTime CurrentReadingDate { get; set; }
        public Nullable<System.DateTime> LastReadingDate { get; set; }
        public int CurrentReadingUnits { get; set; }
    
        public virtual ElectricityMeterMaster ElectricityMeterMaster { get; set; }
    }
}
