//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.PropertyMeterMappings = new HashSet<PropertyMeterMapping>();
            this.RentalProperties = new HashSet<RentalProperty>();
        }
    
        public int Key { get; set; }
        public int PropertyType { get; set; }
        public int PropertyNo { get; set; }
        public string PropertyCaption { get; set; }
        public string PropertyId { get; set; }
        public string AreaCode { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<PropertyMeterMapping> PropertyMeterMappings { get; set; }
        public virtual ICollection<RentalProperty> RentalProperties { get; set; }
    }
}
