//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyMeterMapping
    {
        public int Key { get; set; }
        public int MainPropertyKey { get; set; }
        public int MeterKeyKey { get; set; }
    
        public virtual ElectricityMeterMaster ElectricityMeterMaster { get; set; }
        public virtual Property Property { get; set; }
    }
}
