//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentReceipt
    {
        public int Key { get; set; }
        public int ContractKey { get; set; }
        public int PreviousReceiptKey { get; set; }
        public int MeterReadingKey { get; set; }
        public int PaymentType { get; set; }
        public int PaymentMode { get; set; }
        public decimal DueAmt { get; set; }
        public decimal ReceivedAmt { get; set; }
        public System.DateTime ForMonth { get; set; }
        public int ElectricityUnitRate { get; set; }
        public int ElectricityUnitFrom { get; set; }
        public int ElectricityUnitTo { get; set; }
        public decimal MaintenanceCharge { get; set; }
        public decimal WiFiCharge { get; set; }
        public bool IsWifiOpted { get; set; }
        public decimal RoCharge { get; set; }
        public decimal OtherCharge { get; set; }
        public decimal LastMonthBalance { get; set; }
        public decimal LastMonthAdvance { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public string ReceivedBy { get; set; }
        public bool IsValid { get; set; }
        public bool IsPaymentClear { get; set; }
        public bool IsCanceled { get; set; }
        public bool IsCarryForward { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
