//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalProperty
    {
        public RentalProperty()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int Key { get; set; }
        public int PropertyType { get; set; }
        public int PropertyNo { get; set; }
        public string Caption { get; set; }
        public string CaptionId { get; set; }
        public decimal BaseRentAmount { get; set; }
        public bool IsBooked { get; set; }
        public bool IsVacant { get; set; }
        public bool IsAvailable { get; set; }
        public bool IsNotice { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public Nullable<System.DateTime> AvailableFrom { get; set; }
        public int MeterKey { get; set; }
        public int ParentPropertyKey { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ElectricityMeterMaster ElectricityMeterMaster { get; set; }
        public virtual Property Property { get; set; }
    }
}
