//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentoEntities : DbContext
    {
        public RentoEntities()
            : base("name=RentoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<ElectricityMeterMaster> ElectricityMeterMasters { get; set; }
        public virtual DbSet<ElectricityUnitReading> ElectricityUnitReadings { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertyMeterMapping> PropertyMeterMappings { get; set; }
        public virtual DbSet<RentalProperty> RentalProperties { get; set; }
        public virtual DbSet<RentReceipt> RentReceipts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TenantInfo> TenantInfoes { get; set; }
    }
}
