//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantInfo
    {
        public TenantInfo()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int Key { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string MobileNo1 { get; set; }
        public string MobileNo2 { get; set; }
        public string TempAddress { get; set; }
        public string PermAddress { get; set; }
        public string HomeTelNo1 { get; set; }
        public string HomeTelNo2 { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DeactivationDate { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
